apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        volumeMounts:
        - mountPath: "/var/www/html"
          name: pod-volume-html
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db-password
        ports:
        - name: mysql-port
          containerPort: 3306
      volumes:
      - name: pod-volume-html
        persistentVolumeClaim:
          claimName: jb-claim
        
        
