# JIRA Ticket https://jira.cec.lab.emc.com/browse/CT-602
apiVersion: v1
kind: Pod
metadata:
  name: spring-music
  labels:  # added this - is it necessary?
    app: spring-music
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - spring-music
  containers:
    - name: spring-music
      image: "yanivomc/spring-music:latest"

---

## THIS will start a redis pod as part of the example and affinity rule above
apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    cache: redis
    app: redis-loaded
spec:
    nodeAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - redis-loaded            
  containers:
  - name: redis
    image: redis:latest
