# JIRA Ticket https://jira.cec.lab.emc.com/browse/CT-602
apiVersion: v1
kind: Pod
metadata:
  name: spring-music
  labels:  # added this - is it necessary?
    app: spring-music
spec:
  affinity:
#     podAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: cache
#             operator: In
#             values:
#             - redis
#         topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - spring-music
#         topologyKey: topology.kubernetes.io/zone
  containers:
    - name: spring-music
      image: "yanivomc/spring-music:latest"

---

## THIS will start a redis pod as part of the example and affinity rule above
apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    cache: redis
    app: redis-loaded
spec:
#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#         - matchExpressions:
#           - key: topology.kubernetes.io/zone
#             operator: In
#             values:
#             - eu-west-1b
#             - eu-west-1c
#       preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 1
#         preference:
#           matchExpressions:
#           - key: node.kubernetes.io/instance-type
#             operator: In
#             values:
#             - t3.large
    nodeAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - redis-loaded            
  containers:
  - name: redis
    image: redis:latest
