apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-pod-affinity
  labels:
    app: spring-music
    tier: frontend
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: spring-music
  template:  
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
        - name: springmusic
          image: "yanivomc/spring-music:latest"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cache
                operator: In
                values:
                - redis
            topologyKey: topology.kubernetes.io/zone
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spring-music
            topologyKey: topology.kubernetes.io/zone
            
---

## THIS will start a redis pod as part of the example and affinity rule above
apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    cache: redis
spec:
  containers:
  - name: redis
    image: redis:latest
            
