apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  labels:
{{- include "spring.labels" . | nindent 4  }}
spec:
  selector:
{{- include "spring.labels" . | nindent 4  }}

# IF VALUES.ENV: LOCAL > TYPE: NODEPORT
  {{ if eq .Values.cluster "local" }}
  type: LoadBalancer
  {{ else }}
  type: NodePort
  {{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
